### ISSUE TITLE
Question: how to unbind handler when there is no need for it

### ISSUE THREAD

**Issue by Alendorff** [Xotic750/v-click-outside-x#1]
Hello. As for me, a typical usage of the `v-click-outside` is for closing something. But when element is closed, obviously, there is no need for handler to listen for clicks and to be executed. 

In simple case I can conditionally render element which contains `v-click-outside` with `v-if`, it would be fine then - no unnecessary listeners and calls. But what if I can't use `v-if` for element? Ideally, I would like to remove handler completely when I don't need it. 

Any suggestions how to do that?

**Comment by Xotic750** [comment]
Listeners are added on `bind` for of the element and removed on `unbind`.

https://github.com/Xotic750/v-click-outside-x/blob/master/vClickOutside.js#L110

https://vuejs.org/v2/guide/custom-directive.html#Hook-Functions

**Comment by Alendorff** [comment]
Okay, thanks for an answer. So, I think there is nothing I can do here to controll event setup or remove except with v-if.
