### ISSUE TITLE
Is it possible to upgrade NPM version?

### ISSUE THREAD

**Issue by remiebelingmerifond** [Xotic750/v-click-outside-x#11]
## The problem
First of all, Thanks for your great Module!
It works like a charm. But during npm install I see the following warning:

```
npm WARN notsup Unsupported engine for v-click-outside-x@4.0.19: wanted: {"node":">=8.11.4","npm":"6.10.1"} (current: {"node":"12.13.0","npm":"6.10.1""}) 
npm WARN notsup Not compatible with your version of node/npm: v-click-outside-x@4.0.19 
```

## Details

Would it be possible to set the npm version in package.json to `"npm": ">=6.10.1"`?

Or are there any breaking changes in NPM that prevents you from doing so?

thanks in advance!

**Comment by Xotic750** [comment]
It is probably ok.

**Comment by remiebelingmerifond** [comment]
Allright, 
i created a pull request...
https://github.com/Xotic750/v-click-outside-x/pull/12

**Comment by Xotic750** [comment]
I have updated. Please let me know if you have any problems.
