### ISSUE TITLE
SSR error

### ISSUE THREAD

**Issue by icarusion** [Xotic750/v-click-outside-x#2]
when using in SSR, will throw error, `window not defined`.
![image](https://user-images.githubusercontent.com/5370542/40635464-b982135a-632c-11e8-8076-b1368777cbb2.png)

about this line https://github.com/Xotic750/v-click-outside-x/blob/master/dist/v-click-outside-x.js#L10

**Comment by Xotic750** [comment]
Add `target: "universal"` https://github.com/webpack/webpack/issues/6525

**Comment by Xotic750** [comment]
https://github.com/Xotic750/v-click-outside-x/releases/tag/v2.5.0

**Comment by Xotic750** [comment]
During testing I have found a problem that will require another minor update.

**Comment by Xotic750** [comment]
https://github.com/Xotic750/v-click-outside-x/releases/tag/v2.5.1

**Comment by Xotic750** [comment]
Workaround implemented. Will need to revisit this when Webpack 4 resolves their issue.

**Comment by Xotic750** [comment]
Will change to the solution: https://www.npmjs.com/package/webpack-global-object-x

**Comment by Xotic750** [comment]
Now in v4.0.17
