### ISSUE TITLE
Not support node v15 

### ISSUE THREAD

**Issue by chuantv** [Xotic750/v-click-outside-x#20]
## The problem
I can't install it. 
## Details

npm install --save v-click-outside-x
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'v-click-outside-x@3.7.1',
npm WARN EBADENGINE   required: { node: '>=8.11.4', npm: '6.4.1' },
npm WARN EBADENGINE   current: { node: 'v15.8.0', npm: '7.5.6' }
npm WARN EBADENGINE }

**Comment by SergioCrisostomo** [comment]
Hi @chuantv I made a update recently please retry and let me know if it did work?
