### ISSUE TITLE
webpack5 compatibility issue

### ISSUE THREAD

**Issue by mazhewei** [Xotic750/v-click-outside-x#21]
@SergioCrisostomo 

new repo https://github.com/SergioCrisostomo/v-click-outside-x issues is not enabled.
So i am reply here.
v-click-outside-x has a webpack5 compatibility issue.

webpack5 report this warning:
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)

see webpack5 doc [here](https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules)
It's fast to fix it.

**Comment by SergioCrisostomo** [comment]
Hi @mazhewei !
Thank you for bringing this up!
I enabled issues now, wasn't aware they were not active 🙈 

I pushed an update but now we still need to push it to NPM. I wrote to them also and will try to get them add me as publisher.
If you want you can use the direct link to my repo `https://github.com/SergioCrisostomo/v-click-outside-x@4.1.2` so far.

**Comment by SergioCrisostomo** [comment]
@mazhewei I got a fast answer from NPM and now I can also publish new versions 🎉 
I pushed a new version, please confirm the problem was solved.

**Comment by mazhewei** [comment]
the problem was solved.
i will close this issue.
