### ISSUE TITLE
Node version must greater than 8.11.4

### ISSUE THREAD

**Issue by run27017** [Xotic750/v-click-outside-x#5]
The newest version of v-click-outside-x is 3.5.5, and it will prompts error `The engine "node" is incompatible with this module. Expected version ">=8.11.4"` when installing it. My node version is 8.11.1, would you please explain the features the 8.11.4 has however 8.11.1 hasn't. And I use the vue-cli, which will babel the code.

**Comment by Xotic750** [comment]
https://nodejs.org/en/blog/release/v8.11.1/
https://nodejs.org/en/blog/release/v8.11.2/
https://nodejs.org/en/blog/release/v8.11.3/
https://nodejs.org/en/blog/release/v8.11.4/

**Comment by run27017** [comment]
Ok, sir. I have upgraded to v10 already.

**Comment by aprilandjan** [comment]
Had to upgrade node in order to use `iview` (which required this module) , felt not reasonable, though. This package is used in browser enviroment rather than node.

**Comment by daveykane** [comment]
I agree with @aprilandjan here, this is a client side Vue.js direction, I'm not sure why node is required at all unless I'm missing something.

**Comment by TonyLuo** [comment]
I agree with @aprilandjan. node is no need here...
