### ISSUE TITLE
Why need node version ">=8.11.4" ?

### ISSUE THREAD

**Issue by cdswyda** [Xotic750/v-click-outside-x#7]
## The problem

```bash
error v-click-outside-x@3.7.1: The engine "node" is incompatible with this module. Expected version ">=8.11.4". Got "8.11.2"
```

need node version ">=8.11.4"

## Details

I think this package is used in browser, Is it really need node version limit ?

> v8.11.4 is the version that both myself and my company use. It is the environment that has had the greatest amount of testing on, and for which I can whole heartedly say: "it works".

As your description at [#5](#5) , maybe you can limit it at develop environment , rather than limit the package user.

Although I can upgrade my node version , but it's not convenient, when I upgrade my node version, I still need reinstall some package such as `node-sass` `electron` .

**Comment by Xotic750** [comment]
I have looked at this issue and given it a fair amount of thought. While it may be possible to write a whole bunch of supporting scripts, or change the layout of the project, the amount of effort involved to circumvent how `npm` works seems not worth while. I'm open to suggestions or PRs, if you have an easy way to achieve this or want to spend the time reorganising the project. I haven't tried this but `yarn` has an option to ignore the `engines` entry, you could give that a try: [yarn install --ignore-engines](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines)
